name: terminal-tetris
base: core24
adopt-info: terminal-tetris
summary: Terminal Tetris
description: |
  A terminal-based Tetris game which aims to be a feature-rich implementation of the classic game with modern mechanics.

  **Features**

  * **Classic Tetris Gameplay**: A fully-featured Tetris implementation for the terminal.
  * **GAMEMODES**: We've got Marathon, Sprint, Timed. We even got Garbage.
  * **Modern Mechanics**: Includes advanced mechanics like T-Spin detection and a back-to-back bonus system.
  * **Save state**: Includes a save state feature that allows you to pause the game and resume it later. (hit 's' while game is paused). Saving will close the game. Resume from Main Menu on next startup. **only works on marathon right now**
  * **Hold Functionality**: Swap out the current piece with a stored piece.
  * **Persistent Database**: All high scores and user settings are saved to a local tetris.db file, so your progress and customizations are always remembered.
  * **Settings Menu**: Customize everything from keybindings to game physics and scoring values.
  * **Ghost Piece**: A preview of where the current piece will land. (Toggle in Settings Menu)
  * **High Score Tracking**: The top 5 scores are saved and displayed on the main menu.
  * **Level Progression**: The game's speed increases as you clear more lines.
  * **Proper Lock Delay**: A half-second delay after a piece touches a surface, allowing for last-second adjustments. (adjustable in Settings Menu)
  * **Bag Randomization**: A 7-bag randomization system ensures that all seven tetrominoes will appear in a random order before any are repeated.

grade: stable
confinement: strict
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
issues: https://github.com/kenvandine/terminal-tetris/issues
contact: https://github.com/kenvandine/terminal-tetris/issues
source-code:
  - https://github.com/kenvandine/terminal-tetris
  - https://github.com/averyvisentin/terminal-tetris

parts:
  terminal-tetris:
    plugin: python
    source: .
    python-packages:
      - terminal-tetris
    override-prime: |
      craftctl default
      craftctl set version=$(grep ^Version $CRAFT_PRIME/lib/python3.12/site-packages/terminal_tetris-*.dist-info/METADATA  | awk '{print $2}')

apps:
  terminal-tetris:
    command: bin/terminal-tetris
